### ISSUE TITLE
com.alibaba.dubbo.common.bytecode.NoSuchPropertyException: Not found property "result" filed or setter 

### ISSUE THREAD

**Issue by Neumann789** [Neumann789/dubboClient#2]
请求192.168.224.195:20903耗时：43ms:

Failed to invoke method quickRecharge, cause: com.alibaba.dubbo.common.bytecode.NoSuchPropertyException: Not found property "result" filed or setter method in class com.zb.payment.yw.facade.model.DefaultRsp.
com.alibaba.dubbo.common.bytecode.NoSuchPropertyException: Not found property "result" filed or setter method in class com.zb.payment.yw.facade.model.DefaultRsp.
	at com.alibaba.dubbo.common.bytecode.Wrapper8.getPropertyValue(Wrapper8.java)
	at com.alibaba.dubbo.common.json.GenericJSONConverter.writeValue(GenericJSONConverter.java:125)
	at com.alibaba.dubbo.common.json.JSON.json(JSON.java:143)
	at com.alibaba.dubbo.common.json.JSON.json(JSON.java:94)
	at com.alibaba.dubbo.common.json.JSON.json(JSON.java:86)
	at com.alibaba.dubbo.common.json.JSON.json(JSON.java:71)
	at com.alibaba.dubbo.rpc.protocol.dubbo.telnet.InvokeTelnetHandler.telnet(InvokeTelnetHandler.java:100)
	at com.alibaba.dubbo.remoting.telnet.support.TelnetHandlerAdapter.telnet(TelnetHandlerAdapter.java:54)
	at com.alibaba.dubbo.remoting.excha

**Comment by Neumann789** [comment]
导致上面原因是：InvokeTelnetHandler将dubbo服务的响应对象转JSON的时候报错，报错原因是因为将DefaultRsp中setResult方法解析成result属性来处理了。

![image](https://user-images.githubusercontent.com/11558617/29052161-bf0503ea-7c1a-11e7-8694-c5dd84811101.png)


![image](https://user-images.githubusercontent.com/11558617/29052157-b8202cee-7c1a-11e7-8a19-e99e46c21c8c.png)

![image](https://user-images.githubusercontent.com/11558617/29052167-cfa9e6b6-7c1a-11e7-84cc-c301ef1cb747.png)

**Comment by Neumann789** [comment]
由于dubbo这样恶心的处理逻辑，所有建议定义响应类的时候，如果不想作为属性的，尽量避免使用set或get方法开头

**Comment by alansfa** [comment]
赞
